name: Java CI

on: [push]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache m2 modules
      uses: actions/cache@v1
      env:
        cache-name: cache-m2-modules
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}

    - name: Build with Maven
      run: mvn clean test
      
  deploy-job:
    needs: test-job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache m2 modules
      uses: actions/cache@v1
      env:
        cache-name: cache-m2-modules
      with:
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('pom.xml') }}

    - name: Deploy with Maven
      env:
        GOOGLE_APPLICATION_CREDENTIALS: key.json
      run: |
        echo "${{ secrets.GCP_AUTH }}" | base64 -d > key.json
        mvn package appengine:deploy -DskipTests=true -Dapp.deploy.version=GCLOUD_CONFIG
